/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssignmentRouteImport } from './routes/assignment'
import { Route as DischargeRouteImport } from './routes/discharge'
import { Route as HandoverRouteImport } from './routes/handover'
import { Route as LoginRouteImport } from './routes/login'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as NcpRouteImport } from './routes/ncp'
import { Route as PaperFormsRouteImport } from './routes/paper-forms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RoundsRouteImport } from './routes/rounds'
import { Route as TranquilizerRouteImport } from './routes/tranquilizer'
import { Route as UsersRouteImport } from './routes/users'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AssistantIndexRouteImport } from './routes/assistant/index'
import { Route as AssistantThreadIdRouteImport } from './routes/assistant/$threadId'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsNewRouteImport } from './routes/patients/new'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients/$patientId/index'
import { Route as PatientsPatientIdEditRouteImport } from './routes/patients/$patientId/edit'
import { Route as PrintPatientIdCareplanRouteImport } from './routes/print/$patientId/careplan'
import { Route as PrintPatientIdConsultationRouteImport } from './routes/print/$patientId/consultation'
import { Route as PrintPatientIdNotesRouteImport } from './routes/print/$patientId/notes'
import { Route as PrintPatientIdNursingdbRouteImport } from './routes/print/$patientId/nursingdb'
import { Route as PrintPatientIdProgressRouteImport } from './routes/print/$patientId/progress'
import { Route as PrintPatientIdSbarRouteImport } from './routes/print/$patientId/sbar'
import { Route as PrintPatientIdSummaryRouteImport } from './routes/print/$patientId/summary'
import { Route as PrintPatientIdTreatmentRouteImport } from './routes/print/$patientId/treatment'
import { Route as PrintPatientIdVitalsRouteImport } from './routes/print/$patientId/vitals'
import { Route as PrintAllFormRouteImport } from './routes/print/all.$form'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentRoute = AssignmentRouteImport.update({
  id: '/assignment',
  path: '/assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const DischargeRoute = DischargeRouteImport.update({
  id: '/discharge',
  path: '/discharge',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoverRoute = HandoverRouteImport.update({
  id: '/handover',
  path: '/handover',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const NcpRoute = NcpRouteImport.update({
  id: '/ncp',
  path: '/ncp',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperFormsRoute = PaperFormsRouteImport.update({
  id: '/paper-forms',
  path: '/paper-forms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RoundsRoute = RoundsRouteImport.update({
  id: '/rounds',
  path: '/rounds',
  getParentRoute: () => rootRouteImport,
} as any)
const TranquilizerRoute = TranquilizerRouteImport.update({
  id: '/tranquilizer',
  path: '/tranquilizer',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantThreadIdRoute = AssistantThreadIdRouteImport.update({
  id: '/assistant/$threadId',
  path: '/assistant/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/patients/new',
  path: '/patients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/patients/$patientId/',
  path: '/patients/$patientId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdEditRoute = PatientsPatientIdEditRouteImport.update({
  id: '/patients/$patientId/edit',
  path: '/patients/$patientId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPatientIdCareplanRoute = PrintPatientIdCareplanRouteImport.update({
  id: '/print/$patientId/careplan',
  path: '/print/$patientId/careplan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPatientIdConsultationRoute =
  PrintPatientIdConsultationRouteImport.update({
    id: '/print/$patientId/consultation',
    path: '/print/$patientId/consultation',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrintPatientIdNotesRoute = PrintPatientIdNotesRouteImport.update({
  id: '/print/$patientId/notes',
  path: '/print/$patientId/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPatientIdNursingdbRoute = PrintPatientIdNursingdbRouteImport.update({
  id: '/print/$patientId/nursingdb',
  path: '/print/$patientId/nursingdb',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPatientIdProgressRoute = PrintPatientIdProgressRouteImport.update({
  id: '/print/$patientId/progress',
  path: '/print/$patientId/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPatientIdSbarRoute = PrintPatientIdSbarRouteImport.update({
  id: '/print/$patientId/sbar',
  path: '/print/$patientId/sbar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPatientIdSummaryRoute = PrintPatientIdSummaryRouteImport.update({
  id: '/print/$patientId/summary',
  path: '/print/$patientId/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPatientIdTreatmentRoute = PrintPatientIdTreatmentRouteImport.update({
  id: '/print/$patientId/treatment',
  path: '/print/$patientId/treatment',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintPatientIdVitalsRoute = PrintPatientIdVitalsRouteImport.update({
  id: '/print/$patientId/vitals',
  path: '/print/$patientId/vitals',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintAllFormRoute = PrintAllFormRouteImport.update({
  id: '/print/all/$form',
  path: '/print/all/$form',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assignment': typeof AssignmentRoute
  '/discharge': typeof DischargeRoute
  '/handover': typeof HandoverRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/ncp': typeof NcpRoute
  '/paper-forms': typeof PaperFormsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rounds': typeof RoundsRoute
  '/tranquilizer': typeof TranquilizerRoute
  '/users': typeof UsersRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/assistant/': typeof AssistantIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/print/$patientId/careplan': typeof PrintPatientIdCareplanRoute
  '/print/$patientId/consultation': typeof PrintPatientIdConsultationRoute
  '/print/$patientId/notes': typeof PrintPatientIdNotesRoute
  '/print/$patientId/nursingdb': typeof PrintPatientIdNursingdbRoute
  '/print/$patientId/progress': typeof PrintPatientIdProgressRoute
  '/print/$patientId/sbar': typeof PrintPatientIdSbarRoute
  '/print/$patientId/summary': typeof PrintPatientIdSummaryRoute
  '/print/$patientId/treatment': typeof PrintPatientIdTreatmentRoute
  '/print/$patientId/vitals': typeof PrintPatientIdVitalsRoute
  '/print/all/$form': typeof PrintAllFormRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assignment': typeof AssignmentRoute
  '/discharge': typeof DischargeRoute
  '/handover': typeof HandoverRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/ncp': typeof NcpRoute
  '/paper-forms': typeof PaperFormsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rounds': typeof RoundsRoute
  '/tranquilizer': typeof TranquilizerRoute
  '/users': typeof UsersRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/assistant': typeof AssistantIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/print/$patientId/careplan': typeof PrintPatientIdCareplanRoute
  '/print/$patientId/consultation': typeof PrintPatientIdConsultationRoute
  '/print/$patientId/notes': typeof PrintPatientIdNotesRoute
  '/print/$patientId/nursingdb': typeof PrintPatientIdNursingdbRoute
  '/print/$patientId/progress': typeof PrintPatientIdProgressRoute
  '/print/$patientId/sbar': typeof PrintPatientIdSbarRoute
  '/print/$patientId/summary': typeof PrintPatientIdSummaryRoute
  '/print/$patientId/treatment': typeof PrintPatientIdTreatmentRoute
  '/print/$patientId/vitals': typeof PrintPatientIdVitalsRoute
  '/print/all/$form': typeof PrintAllFormRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assignment': typeof AssignmentRoute
  '/discharge': typeof DischargeRoute
  '/handover': typeof HandoverRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/ncp': typeof NcpRoute
  '/paper-forms': typeof PaperFormsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rounds': typeof RoundsRoute
  '/tranquilizer': typeof TranquilizerRoute
  '/users': typeof UsersRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/assistant/$threadId': typeof AssistantThreadIdRoute
  '/patients/new': typeof PatientsNewRoute
  '/assistant/': typeof AssistantIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/patients/$patientId/edit': typeof PatientsPatientIdEditRoute
  '/print/$patientId/careplan': typeof PrintPatientIdCareplanRoute
  '/print/$patientId/consultation': typeof PrintPatientIdConsultationRoute
  '/print/$patientId/notes': typeof PrintPatientIdNotesRoute
  '/print/$patientId/nursingdb': typeof PrintPatientIdNursingdbRoute
  '/print/$patientId/progress': typeof PrintPatientIdProgressRoute
  '/print/$patientId/sbar': typeof PrintPatientIdSbarRoute
  '/print/$patientId/summary': typeof PrintPatientIdSummaryRoute
  '/print/$patientId/treatment': typeof PrintPatientIdTreatmentRoute
  '/print/$patientId/vitals': typeof PrintPatientIdVitalsRoute
  '/print/all/$form': typeof PrintAllFormRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assignment'
    | '/discharge'
    | '/handover'
    | '/login'
    | '/mcp'
    | '/ncp'
    | '/paper-forms'
    | '/reset-password'
    | '/rounds'
    | '/tranquilizer'
    | '/users'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/patients/new'
    | '/assistant/'
    | '/patients/'
    | '/.lovable/oauth/consent'
    | '/patients/$patientId/edit'
    | '/print/$patientId/careplan'
    | '/print/$patientId/consultation'
    | '/print/$patientId/notes'
    | '/print/$patientId/nursingdb'
    | '/print/$patientId/progress'
    | '/print/$patientId/sbar'
    | '/print/$patientId/summary'
    | '/print/$patientId/treatment'
    | '/print/$patientId/vitals'
    | '/print/all/$form'
    | '/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assignment'
    | '/discharge'
    | '/handover'
    | '/login'
    | '/mcp'
    | '/ncp'
    | '/paper-forms'
    | '/reset-password'
    | '/rounds'
    | '/tranquilizer'
    | '/users'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/patients/new'
    | '/assistant'
    | '/patients'
    | '/.lovable/oauth/consent'
    | '/patients/$patientId/edit'
    | '/print/$patientId/careplan'
    | '/print/$patientId/consultation'
    | '/print/$patientId/notes'
    | '/print/$patientId/nursingdb'
    | '/print/$patientId/progress'
    | '/print/$patientId/sbar'
    | '/print/$patientId/summary'
    | '/print/$patientId/treatment'
    | '/print/$patientId/vitals'
    | '/print/all/$form'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/assignment'
    | '/discharge'
    | '/handover'
    | '/login'
    | '/mcp'
    | '/ncp'
    | '/paper-forms'
    | '/reset-password'
    | '/rounds'
    | '/tranquilizer'
    | '/users'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/assistant/$threadId'
    | '/patients/new'
    | '/assistant/'
    | '/patients/'
    | '/.lovable/oauth/consent'
    | '/patients/$patientId/edit'
    | '/print/$patientId/careplan'
    | '/print/$patientId/consultation'
    | '/print/$patientId/notes'
    | '/print/$patientId/nursingdb'
    | '/print/$patientId/progress'
    | '/print/$patientId/sbar'
    | '/print/$patientId/summary'
    | '/print/$patientId/treatment'
    | '/print/$patientId/vitals'
    | '/print/all/$form'
    | '/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssignmentRoute: typeof AssignmentRoute
  DischargeRoute: typeof DischargeRoute
  HandoverRoute: typeof HandoverRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  NcpRoute: typeof NcpRoute
  PaperFormsRoute: typeof PaperFormsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoundsRoute: typeof RoundsRoute
  TranquilizerRoute: typeof TranquilizerRoute
  UsersRoute: typeof UsersRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  AssistantThreadIdRoute: typeof AssistantThreadIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  PatientsPatientIdEditRoute: typeof PatientsPatientIdEditRoute
  PrintPatientIdCareplanRoute: typeof PrintPatientIdCareplanRoute
  PrintPatientIdConsultationRoute: typeof PrintPatientIdConsultationRoute
  PrintPatientIdNotesRoute: typeof PrintPatientIdNotesRoute
  PrintPatientIdNursingdbRoute: typeof PrintPatientIdNursingdbRoute
  PrintPatientIdProgressRoute: typeof PrintPatientIdProgressRoute
  PrintPatientIdSbarRoute: typeof PrintPatientIdSbarRoute
  PrintPatientIdSummaryRoute: typeof PrintPatientIdSummaryRoute
  PrintPatientIdTreatmentRoute: typeof PrintPatientIdTreatmentRoute
  PrintPatientIdVitalsRoute: typeof PrintPatientIdVitalsRoute
  PrintAllFormRoute: typeof PrintAllFormRoute
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignment': {
      id: '/assignment'
      path: '/assignment'
      fullPath: '/assignment'
      preLoaderRoute: typeof AssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discharge': {
      id: '/discharge'
      path: '/discharge'
      fullPath: '/discharge'
      preLoaderRoute: typeof DischargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handover': {
      id: '/handover'
      path: '/handover'
      fullPath: '/handover'
      preLoaderRoute: typeof HandoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncp': {
      id: '/ncp'
      path: '/ncp'
      fullPath: '/ncp'
      preLoaderRoute: typeof NcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper-forms': {
      id: '/paper-forms'
      path: '/paper-forms'
      fullPath: '/paper-forms'
      preLoaderRoute: typeof PaperFormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rounds': {
      id: '/rounds'
      path: '/rounds'
      fullPath: '/rounds'
      preLoaderRoute: typeof RoundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tranquilizer': {
      id: '/tranquilizer'
      path: '/tranquilizer'
      fullPath: '/tranquilizer'
      preLoaderRoute: typeof TranquilizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/$threadId': {
      id: '/assistant/$threadId'
      path: '/assistant/$threadId'
      fullPath: '/assistant/$threadId'
      preLoaderRoute: typeof AssistantThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/patients/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId/edit': {
      id: '/patients/$patientId/edit'
      path: '/patients/$patientId/edit'
      fullPath: '/patients/$patientId/edit'
      preLoaderRoute: typeof PatientsPatientIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$patientId/careplan': {
      id: '/print/$patientId/careplan'
      path: '/print/$patientId/careplan'
      fullPath: '/print/$patientId/careplan'
      preLoaderRoute: typeof PrintPatientIdCareplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$patientId/consultation': {
      id: '/print/$patientId/consultation'
      path: '/print/$patientId/consultation'
      fullPath: '/print/$patientId/consultation'
      preLoaderRoute: typeof PrintPatientIdConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$patientId/notes': {
      id: '/print/$patientId/notes'
      path: '/print/$patientId/notes'
      fullPath: '/print/$patientId/notes'
      preLoaderRoute: typeof PrintPatientIdNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$patientId/nursingdb': {
      id: '/print/$patientId/nursingdb'
      path: '/print/$patientId/nursingdb'
      fullPath: '/print/$patientId/nursingdb'
      preLoaderRoute: typeof PrintPatientIdNursingdbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$patientId/progress': {
      id: '/print/$patientId/progress'
      path: '/print/$patientId/progress'
      fullPath: '/print/$patientId/progress'
      preLoaderRoute: typeof PrintPatientIdProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$patientId/sbar': {
      id: '/print/$patientId/sbar'
      path: '/print/$patientId/sbar'
      fullPath: '/print/$patientId/sbar'
      preLoaderRoute: typeof PrintPatientIdSbarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$patientId/summary': {
      id: '/print/$patientId/summary'
      path: '/print/$patientId/summary'
      fullPath: '/print/$patientId/summary'
      preLoaderRoute: typeof PrintPatientIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$patientId/treatment': {
      id: '/print/$patientId/treatment'
      path: '/print/$patientId/treatment'
      fullPath: '/print/$patientId/treatment'
      preLoaderRoute: typeof PrintPatientIdTreatmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$patientId/vitals': {
      id: '/print/$patientId/vitals'
      path: '/print/$patientId/vitals'
      fullPath: '/print/$patientId/vitals'
      preLoaderRoute: typeof PrintPatientIdVitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/all/$form': {
      id: '/print/all/$form'
      path: '/print/all/$form'
      fullPath: '/print/all/$form'
      preLoaderRoute: typeof PrintAllFormRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssignmentRoute: AssignmentRoute,
  DischargeRoute: DischargeRoute,
  HandoverRoute: HandoverRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  NcpRoute: NcpRoute,
  PaperFormsRoute: PaperFormsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoundsRoute: RoundsRoute,
  TranquilizerRoute: TranquilizerRoute,
  UsersRoute: UsersRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  AssistantThreadIdRoute: AssistantThreadIdRoute,
  PatientsNewRoute: PatientsNewRoute,
  AssistantIndexRoute: AssistantIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  PatientsPatientIdEditRoute: PatientsPatientIdEditRoute,
  PrintPatientIdCareplanRoute: PrintPatientIdCareplanRoute,
  PrintPatientIdConsultationRoute: PrintPatientIdConsultationRoute,
  PrintPatientIdNotesRoute: PrintPatientIdNotesRoute,
  PrintPatientIdNursingdbRoute: PrintPatientIdNursingdbRoute,
  PrintPatientIdProgressRoute: PrintPatientIdProgressRoute,
  PrintPatientIdSbarRoute: PrintPatientIdSbarRoute,
  PrintPatientIdSummaryRoute: PrintPatientIdSummaryRoute,
  PrintPatientIdTreatmentRoute: PrintPatientIdTreatmentRoute,
  PrintPatientIdVitalsRoute: PrintPatientIdVitalsRoute,
  PrintAllFormRoute: PrintAllFormRoute,
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
